// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0vULRq962FK-aAj-_mrTOUUk6gUnPSg',
    appId: '1:600465649440:web:47aeac3dbdfea7dd81b145',
    messagingSenderId: '600465649440',
    projectId: 'ar-smart-78671',
    authDomain: 'ar-smart-78671.firebaseapp.com',
    storageBucket: 'ar-smart-78671.firebasestorage.app',
    measurementId: 'G-9PS15B5LPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTujZmzUCPDW9iPjwR8ne39QVNaCHMCs',
    appId: '1:600465649440:android:4b3678ea54c6212581b145',
    messagingSenderId: '600465649440',
    projectId: 'ar-smart-78671',
    storageBucket: 'ar-smart-78671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkn2wGf_ObJjZyPEmSfkf6em0wFNW2qDo',
    appId: '1:600465649440:ios:620a709407fcf0cb81b145',
    messagingSenderId: '600465649440',
    projectId: 'ar-smart-78671',
    storageBucket: 'ar-smart-78671.firebasestorage.app',
    iosBundleId: 'com.example.arsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkn2wGf_ObJjZyPEmSfkf6em0wFNW2qDo',
    appId: '1:600465649440:ios:620a709407fcf0cb81b145',
    messagingSenderId: '600465649440',
    projectId: 'ar-smart-78671',
    storageBucket: 'ar-smart-78671.firebasestorage.app',
    iosBundleId: 'com.example.arsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0vULRq962FK-aAj-_mrTOUUk6gUnPSg',
    appId: '1:600465649440:web:d97830dc3ec6dd2381b145',
    messagingSenderId: '600465649440',
    projectId: 'ar-smart-78671',
    authDomain: 'ar-smart-78671.firebaseapp.com',
    storageBucket: 'ar-smart-78671.firebasestorage.app',
    measurementId: 'G-WS4G5XRXX6',
  );
}
